# Generated by Django 3.0.7 on 2020-06-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_subsribers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='Subsribers',
        ),
    ]
