# Generated by Django 3.0.7 on 2020-06-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200608_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsriber',
            options={'verbose_name': 'MySubsriber', 'verbose_name_plural': 'A lot of Subsribers'},
        ),
    ]
